### ISSUE TITLE
Some of the 6 screenshots are darker or lighter than the others

### ISSUE THREAD

**Issue by Brxnni** [PepiHax/Pano360Cam#1]
When making the 6 screenshots for the cubic map, some of them turn out lighter than the others, resulting in something like this: (Equirectangular map stitched together)

![Equirectangular Map](https://user-images.githubusercontent.com/72916383/185104523-73700f36-3cdb-4edc-a764-d690864cd66f.png)

I already tried using the PermaDay mod because I thought it could be caused by the daytime changing while making the screenshots, but that was not the cause.

**Comment by PepiHax** [comment]
Hi, i cant recreate these lighting condition? could you post a picture of your ingame settings?
Also in hugin under stiching, theres a setting called something like exposure correction, try that setting.

**Comment by Brxnni** [comment]
Thanks for responding!

My settings are as follows:

![__settings1](https://user-images.githubusercontent.com/72916383/185212753-5b44b6d8-8700-4b74-a7d6-1e2e6fdf57b3.png)
![__settings2](https://user-images.githubusercontent.com/72916383/185212756-3019758d-aaf8-4133-812f-f888613ead1a.png)

Using the Hugin exposure correction worked perfectly, but I need to stitch hundreds of panoramas, so I would need to find a way to either automate that or change my settings.

**Comment by PepiHax** [comment]
Good you got it to work, you can simply set the setting and then save the pto file again, then run it with the console. i cannot tell you how to do it, but there are some hugin tutorials around.

**Comment by Brxnni** [comment]
Thanks! I did not know you could control Hugin with the console. I was trying to automate this in Python, and I was stitching the images myself.
